@echo off
echo Starting AIS-catcher...
start "" "C:\AIS-catcher.x64\AIS-catcher" -v 10 -X -u 127.0.0.1 10110 -N 8100 PLUGIN_DIR "C:\AIS-catcher.x64\plugins"
echo Waiting 5 seconds for AIS-catcher to boot...
timeout /t 5
echo Starting relay to quynhonlife.com...
node C:\ais-relay.js
PAUSE
